export enum ResponseStatuses {
    REACTION_SET_SUCCESSFULLY = "REACTION_SET_SUCCESSFULLY",
    REACTION_SET_ERROR = "REACTION_SET_ERROR",

    COMMENT_CREATED_SUCCESSFULLY = "COMMENT_CREATED_SUCCESSFULLY",

    POST_CREATED_SUCCESSFULLY = "POST_CREATED_SUCCESSFULLY"
}